// مصدر البيانات الرئيسي للروابط
// يمكنك التعديل والإضافة كما تشاء

const LINKS_DATA = [
  {
    id: 1,
    title: "مدونة CSS-Tricks",
    description: "مقالات وأمثلة عملية حول CSS وواجهات المستخدم.",
    url: "https://css-tricks.com",
    category: "مدونات",
    tags: ["واجهة المستخدم", "CSS", "تصميم"],
  },
  {
    id: 2,
    title: "Smashing Magazine",
    description: "مجلة للمصممين والمطورين تهتم بأفضل الممارسات.",
    url: "https://www.smashingmagazine.com",
    category: "مدونات",
    tags: ["تصميم", "تجربة المستخدم", "واجهات"],
  },
  {
    id: 3,
    title: "BBC Arabic",
    description: "أخبار عالمية وعربية محدثة على مدار الساعة.",
    url: "https://www.bbc.com/arabic",
    category: "أخبار",
    tags: ["أخبار", "سياسة"],
  },
  {
    id: 4,
    title: "Al Jazeera",
    description: "موقع قناة الجزيرة الإخبارية.",
    url: "https://www.aljazeera.net",
    category: "أخبار",
    tags: ["أخبار", "تقارير"],
  },
  {
    id: 5,
    title: "MDN Web Docs",
    description: "مرجع موثوق لتقنيات الويب (HTML, CSS, JS).",
    url: "https://developer.mozilla.org",
    category: "تعليمي",
    tags: ["HTML", "CSS", "JavaScript", "مرجع"],
  },
  {
    id: 6,
    title: "freeCodeCamp",
    description: "منصة تعليمية لتعلّم البرمجة بالمشاريع العملية.",
    url: "https://www.freecodecamp.org",
    category: "تعليمي",
    tags: ["تعليم", "مشاريع", "برمجة"],
  },
  {
    id: 7,
    title: "Coursera",
    description: "دورات من جامعات وشركات عالمية.",
    url: "https://www.coursera.org",
    category: "منصات",
    tags: ["تعليم", "دورات", "جامعات"],
  },
  {
    id: 8,
    title: "LinkedIn",
    description: "شبكة مهنية لمتابعة الشركات والمصممين والمطورين.",
    url: "https://www.linkedin.com",
    category: "منصات",
    tags: ["شبكات", "شركات", "مهنة"],
  },
  {
    id: 9,
    title: "Dribbble",
    description: "أعمال مصممين وإلهام بصري للواجهات.",
    url: "https://dribbble.com",
    category: "إلهام بصري",
    tags: ["تصميم", "واجهات", "إلهام"],
  },
  {
    id: 10,
    title: "Behance",
    description: "معرض أعمال إبداعية من مختلف المجالات.",
    url: "https://www.behance.net",
    category: "إلهام بصري",
    tags: ["تصميم", "هويات", "إلهام"],
  },
  {
    id: 11,
    title: "Stripe",
    description: "شركة حلول دفع إلكتروني، بواجهة نظيفة وحديثة.",
    url: "https://stripe.com",
    category: "شركات",
    tags: ["واجهات", "شركات", "منتجات"],
  },
  {
    id: 12,
    title: "Dropbox",
    description: "خدمة تخزين سحابي بتصميم بسيط.",
    url: "https://www.dropbox.com",
    category: "شركات",
    tags: ["منتجات", "تخزين", "واجهات"],
  },
  {
    id: 13,
    title: "البنك الأهلي السعودي",
    description: "أحد أكبر البنوك السعودية بواجهة عربية.",
    url: "https://www.alahli.com",
    category: "بنوك",
    tags: ["بنوك", "مالية"],
  },
  {
    id: 14,
    title: "مصرف الراجحي",
    description: "موقع مصرف الراجحي للخدمات المصرفية.",
    url: "https://www.alrajhibank.com.sa",
    category: "بنوك",
    tags: ["بنوك", "مالية"],
  },
  {
    id: 15,
    title: "Awwwards",
    description: "مواقع فائزة بجوائز في التصميم وتجربة المستخدم.",
    url: "https://www.awwwards.com",
    category: "إلهام بصري",
    tags: ["جائزة", "تصميم", "واجهات"],
  },
];

